name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        check:
          - isort --check .
          - black --check .
          - flake8 .
          - mypy .
        python_version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: uv sync --locked

      - name: Run linter
        run: uv run ${{ matrix.check }}
