name: release

on:
  push:
    tags:
      - "v*"

env:
  UV_PUBLISH_TOKEN: "${{ secrets.PYPI_TOKEN }}"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          python-version: "3.11"

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
