name: release

on:
  push:
    tags:
      - "v*"

env:
  POETRY_PYPI_TOKEN_PYPI: "${{ secrets.PYPI_TOKEN }}"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Poetry
        uses: snok/install-poetry@v1.3
        with:
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Poetry publish
        run: poetry publish --build
