name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.11", "3.12"]

    name: Python ${{ matrix.python-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-${{ matrix.python_version }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Set up Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install

      - name: Run test
        run: |
          poetry run pytest
