name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.11", "3.12"]

    name: Python ${{ matrix.python_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: uv sync --locked

      - name: Run test
        run: uv run pytest
